# Generated by Django 3.1.3 on 2020-11-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballleagues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='createdby',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='createddate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='numberofteams',
            new_name='number_of_teams',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='updatedby',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='updateddate',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='createdby',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='createddate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='updatedby',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='updateddate',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='createdby',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='createddate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='updatedby',
            new_name='updated_by',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='updateddate',
            new_name='updated_date',
        ),
    ]
