# Generated by Django 3.1.3 on 2020-11-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0003_team_coach"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="league_id",
                to="footballleagues.team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="league_id",
                to="footballleagues.league",
            ),
        ),
        migrations.AlterField(
            model_name="league",
            name="current_champion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="league",
            name="most_appearances",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="league",
            name="most_championships",
            field=models.TextField(blank=True),
        ),
    ]
