# Generated by Django 3.1.3 on 2020-11-13 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0004_auto_20201113_1926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="team",
                to="footballleagues.team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="league",
                to="footballleagues.league",
            ),
        ),
    ]
