# Generated by Django 3.1.3 on 2020-11-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0007_auto_20201114_1551"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=[
                    "name",
                    "city",
                    "coach",
                    "championships_won",
                    "number_of_players",
                ],
                name="team_idx",
            ),
        ),
    ]
