# Generated by Django 3.1.3 on 2020-11-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0008_auto_20201114_1554"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="player",
            name="player_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="team",
            name="team_idx",
        ),
    ]
