# Generated by Django 3.1.3 on 2020-11-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0010_auto_20201114_2103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="number_of_teams",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
