# Generated by Django 3.1.3 on 2020-11-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0012_auto_20201115_2242"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["name"], name="player_name_idx"),
        ),
    ]
