# Generated by Django 3.1.3 on 2020-11-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0013_auto_20201115_2256"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="player",
            name="player_name_idx",
        ),
    ]
