# Generated by Django 3.1.3 on 2020-11-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0016_auto_20201116_1250"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="player",
            name="player_name_idx",
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
