# Generated by Django 3.1.3 on 2020-11-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0017_auto_20201116_1254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["name"], name="player_name_idx"),
        ),
    ]
