# Generated by Django 3.1.3 on 2020-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0018_auto_20201116_1256"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="player",
            name="player_name_idx",
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="team",
            name="championships_won",
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="number_of_players",
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
