# Generated by Django 3.1.3 on 2020-11-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0019_auto_20201116_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
