# Generated by Django 3.1.3 on 2020-11-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballleagues', '0021_auto_20201116_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
