# Generated by Django 3.1.3 on 2020-11-16 13:24

from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("footballleagues", "0022_auto_20201116_1324"),
    ]

    operations = [TrigramExtension()]
